version: "3.8"

services:
  db:
    container_name: injdb
    image: postgres:latest
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - inj
    environment:
      - POSTGRES_DB=injdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3344:3344
      - 5555:5555
    expose:
      - 3344
      - 5555
    networks:
      - inj
    links:
      - db
    env_file:
      - .env
    platform: "linux/amd64"
    depends_on:
      - db

networks:
  inj:
    driver: bridge